apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ticket-deployment
  labels:
    app: service-ticket
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-ticket
  template:
    metadata:
      labels:
        app: service-ticket
    spec:
      containers:
      - name: service-ticket
        image: 735542962543.dkr.ecr.eu-west-2.amazonaws.com/service-ticket:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: QUEUE_URL
            value: http://localhost:4566/000000000000/order-stored-queue
          - name: AWS_REGION
            value: eu-west-2
          - name: GRPC_HOST
            value: localhost
          - name: GRPC_PORT
            value: "50002"
          - name: MAIL_HOST
            value: localhost
          - name: MAIL_PORT
            value: "1025"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"